---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:  ext-grafana-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  refreshInterval: "1h"
  target:
    name: grafana-proxy
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        session_secret: "{{ .session_secret }}"
  data:
    - secretKey: session_secret
      remoteRef:
        key: GRAFANA_SESSION_SECRET