apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../base
    ## DO NOT INCLUDE SECRET HERE.
    ##
    #- doppler-secret.yaml

    # Secret store
    - doppler-secretstore.yaml

    # The new Red Hat operator deploys Network Policy
    # Which restricts internet access for some reason.
    - networkpolicy.yaml