apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sigaint-monitoring
resources:
  - ../../base
  - loki-s3-secret.yaml
patches:
  - target:
      kind: LokiStack
      name: loki-stack
    patch: |-
      - op: replace
        path: /spec/tenants/mode
        value: "static"

