apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../base
patches:
- target:
    kind: Certificate
    name: apiserver-tls
  patch: |-
    - op: replace
      path: /spec/commonName
      value: "api.hub.sigaint.au"
    - op: replace
      path: /spec/dnsNames
      value:
        - "api.hub.sigaint.au"
    - op: replace
      path: /spec/issuerRef/name
      value: le-production
- target:
    kind: APIServer
    name: cluster
  patch: |-
    - op: replace
      path: /spec/servingCerts/namedCertificates
      value:
      - names:
          - "api.hub.sigaint.au"
        servingCertificate:
          name: apiserver-tls