---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base/operator
  - ../../base/instance
  - create-cluster-auth-job.yaml
  - profiles/e8-tailored-profile-scc.yaml
  - scans/weekly-scan.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: rhacs-operator

  - path: patch-central.yaml
    target:
      group: platform.stackrox.io
      kind: Central
      name: central
      version: v1alpha1
