---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: rhacs-operator
resources:
  - ../../base/operator
  - ../../base/instance

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
    target:
      kind: Subscription
      name: rhacs-operator

  - path: patch-resources.yaml
    target:
      group: platform.stackrox.io
      kind: Central
      name: central
      version: v1alpha1
