apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
spec:
  controllerConfig:
    networkPolicies:
      - name: allow-external-secrets-egress
        componentName: ExternalSecretsCoreController
        egress: []
    plugins:
      bitwardenSecretManagerProvider:
        mode: Enabled
