apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  labels:
    app.kubernetes.io/name: cluster
  name: cluster
spec:
  appConfig:
    logLevel: 3
  webhookConfig:
    certificateCheckInterval: 5m0s
    mode: Enabled
    networkPolicies:
      - componentName: ExternalSecretsCoreController
        egress:
          - ports:
              - port: 443
                protocol: TCP
              - port: 9998
                protocol: TCP
            name: allow-external-secrets-egress
    plugins:
      bitwardenSecretManagerProvider:
        mode: Enabled